/**
 * You can find all the mocked responses in this file
 */

import {DeliveryService} from '../../enum';
import {
  //ICartResponse,
  ICusomerDeliverableAddress,
} from '../../module/food/cart/types';
//import {CouponLevel, CouponType} from '../../module/food/coupons/enum';

export const valid_cart_request = {
  action: 'UPDATE',
  customer_device_id: '12412423432424413213123',
  customer_address_id: 'bd7e895f-0f7d-4dbe-9408-285abf5986ce',
  restaurant_id: 'b0909e52-a731-4665-a791-ee6479008805',
  menu_items: [
    {
      quantity: 1,
      menu_item_id: 11101,
      variant_groups: [
        {
          variant_group_id: 98,
          variant_id: 998,
        },
        {
          variant_group_id: 99,
          variant_id: 999,
        },
      ],
      addon_groups: [
        {
          addon_group_id: 77,
          addons: [7767, 7768],
        },
      ],
    },
  ],
  any_special_request: 'Dont ring door bell',
};

export const delivery_address: ICusomerDeliverableAddress = {
  apartment_road_area: 'apartment_road_area.',
  city: 'Mumbai',
  country: 'India',
  created_at: '2022-02-24T06:25:22.096Z',
  customer_id: '33c6fdbc-8df6-4541-9d3f-f9e5ba4c0242',
  directions: 'ABC',
  house_flat_block_no: 'HouseNumber,Wing,Block Number,',
  id: 'bd7e895f-0f7d-4dbe-9408-285abf5986ce',
  deliverable: true,
  latitude: 19.158672,
  longitude: 72.89071,
  name: 'Mohit',
  pincode: '0',
  state: 'Maharashtra',
  updated_at: '2022-02-24T06:25:22.096Z',
  delivery_details: {
    pickup_eta: 1,
    drop_eta: 35,
    deliverable: true,
    delivery_cost: 59,
    delivery_service: (process.env.DELIVERY_SERVICE ||
      DeliveryService.SHADOWFAX) as DeliveryService,
  },
};
export const speedyy_rider_serviceable_delivery_address: ICusomerDeliverableAddress =
  {
    apartment_road_area: 'apartment_road_area.',
    city: 'Mumbai',
    country: 'India',
    created_at: '2022-02-24T06:25:22.096Z',
    customer_id: '33c6fdbc-8df6-4541-9d3f-f9e5ba4c0242',
    directions: 'ABC',
    house_flat_block_no: 'HouseNumber,Wing,Block Number,',
    id: 'bd7e895f-0f7d-4dbe-9408-285abf5986ce',
    deliverable: true,
    latitude: 19.158672,
    longitude: 72.89071,
    name: 'Mohit',
    pincode: '0',
    state: 'Maharashtra',
    updated_at: '2022-02-24T06:25:22.096Z',
    delivery_details: {
      pickup_eta: 1,
      drop_eta: 35,
      deliverable: true,
      delivery_cost: 59,
      delivery_service: (process.env.DELIVERY_SERVICE ||
        DeliveryService.SHADOWFAX) as DeliveryService,
      pod_allowed: true,
    },
  };

export const customer_addresses = [
  {
    apartment_road_area: 'apartment_road_area.',
    city: 'Mumbai',
    country: 'India',
    created_at: '2022-02-24T06:25:22.096Z',
    customer_id: '33c6fdbc-8df6-4541-9d3f-f9e5ba4c0242',
    directions: 'ABC',
    house_flat_block_no: 'HouseNumber,Wing,Block Number,',
    id: 'bd7e895f-0f7d-4dbe-9408-285abf5986ce',
    latitude: 19.158672,
    longitude: 72.89071,
    name: 'Mohit',
    pincode: '0',
    state: 'Maharashtra',
    updated_at: '2022-02-24T06:25:22.096Z',
  },
];

export const PaymentTableResponse = {
  id: '',
  order_id: '',
  customer_id: '33c6fdbc-8df6-4541-9d3f-f9e5ba4c0242',
  transaction_token: 'caaea734a6f74e0d8812ca89d6868f401653376383820',
  payment_status: 'completed',
  created_at: '',
  updated_at: '',
  // total_bill: 211,
  transaction_time: '2022-06-10T14:04:19.480Z',
};

export const cartResponse = {
  cancellation_policy: {
    terms_conditions: 'https://www.speedyy.com/terms-conditions/',
    note: 'If you cancel within 60 seconds of placing your order, a 100% refund will be issued. No refund for cancellation made after 60 seconds.',
  },
  customer_details: {
    customer_id: '33c6fdbc-8df6-4541-9d3f-f9e5ba4c0242',
    customer_device_id: '12412423432424413213123',
    customer_address_id: 'bd7e895f-0f7d-4dbe-9408-285abf5986ce',
    customer_addresses: [delivery_address],
    delivery_address: delivery_address,
  },
  any_special_request: 'Dont ring door bell',

  menu_items_available: true,

  menu_items: [
    {
      menu_item_id: 11101,
      restaurant_id: 'b0909e52-a731-4665-a791-ee6479008805',
      menu_item_name: 'Veg Burger',
      sub_category_id: 111,
      description: 'description',
      price: 100,
      veg_egg_non: 'veg',
      packing_charges: 10,
      is_spicy: true,
      serves_how_many: 1,
      service_charges: 10,
      item_sgst_utgst: 0,
      item_cgst: 0,
      item_igst: 0,
      item_inclusive: true,
      disable: false,
      external_id: '123',
      image: {},
      allow_long_distance: true,
      next_available_after: '2022-04-27T04:54:01.883Z',
      is_deleted: false,
      variant_groups: [
        {
          variant_group_id: 98,
          variant_group_name: 'menu item 1 variant 1',
          variants: [
            {
              variant_id: 998,
              variant_group_id: 98,
              variant_name: 'variant group 1 variant name',
              is_default: true,
              price: 10,
              veg_egg_non: 'veg',
              in_stock: true,
              serves_how_many: 1,
              is_selected: true,
            },
          ],
          is_selected: true,
        },
        {
          variant_group_id: 99,
          variant_group_name: 'menu item 1 variant 2',
          variants: [
            {
              variant_id: 999,
              variant_group_id: 99,
              variant_name: 'variant group 1 variant name',
              is_default: true,
              price: 10,
              veg_egg_non: 'veg',
              in_stock: true,
              serves_how_many: 1,
              is_selected: true,
            },
          ],
          is_selected: true,
        },
      ],
      addon_groups: [
        {
          addon_group_id: 77,
          addon_group_name: 'addon group name',
          min_limit: 2,
          max_limit: 3,
          free_limit: 1,
          sequence: 1,
          addons: [
            {
              addon_id: 7768,
              addon_name: 'addon name 2',
              cgst_rate: 0,
              external_id: '76778',
              gst_inclusive: true,
              igst_rate: 0,
              in_stock: true,
              is_selected: true,
              price: 10,
              sequence: 1,
              sgst_rate: 0,
              veg_egg_non: 'veg',
            },
            {
              addon_id: 7769,
              addon_name: 'addon name 3',
              cgst_rate: 0,
              external_id: '76779',
              gst_inclusive: true,
              igst_rate: 0,
              in_stock: true,
              is_selected: false,
              price: 10,
              sequence: 1,
              sgst_rate: 0,
              veg_egg_non: 'veg',
            },
            {
              addon_id: 7767,
              addon_name: 'addon name 1',
              sequence: 1,
              price: 12,
              veg_egg_non: 'veg',
              in_stock: true,
              sgst_rate: 0,
              cgst_rate: 0,
              igst_rate: 0,
              gst_inclusive: true,
              external_id: '76777',
              is_selected: true,
            },
          ],
          is_selected: true,
        },
      ],
      menu_item_slots: null,
      quantity: 1,
      variants_total_cost_without_tax: 20,
      variants_instock: true,
      variants_count: 2,
      addons_total_cost_without_tax: 22,
      addons_total_tax: 0,
      addons_instock: true,
      addons_count: 2,
      total_tax: 0,
      total_cost_without_tax: 152,
      in_stock: true,
    },
  ],
  menu_items_count: 1,
  delivery_time: 47,
  restaurant_details: {
    availability: {
      is_holiday: false,
      is_open: true,
    },
    restaurant_id: 'b0909e52-a731-4665-a791-ee6479008805',
    restaurant_name: 'Burger King',
    restaurant_status: 'active',
    rating: 0, //! BACKWARD_COMPATIBLE
    like_count: 100000,
    like_count_label: '100.0K',
  },

  invoice_breakout: {
    total_tax: 0,
    total_customer_payable: 191,
    delivery_charges: 59,
    // packing_charges: 0,
    // offer_discount: 0,
  },
  cart_status: true,
};

export const menuItemWithNoVariantsAddons = {
  cancellation_policy: {
    terms_conditions: 'https://www.speedyy.com/terms-conditions/',
    note: 'If you cancel within 60 seconds of placing your order, a 100% refund will be issued. No refund for cancellation made after 60 seconds.',
  },
  customer_details: {
    customer_addresses: [delivery_address],
    customer_id: '33c6fdbc-8df6-4541-9d3f-f9e5ba4c0242',
    customer_address_id: 'bd7e895f-0f7d-4dbe-9408-285abf5986ce',
    delivery_address: delivery_address,
  },

  menu_items_available: true,
  menu_items: [
    {
      menu_item_id: 11102,
      restaurant_id: 'b0909e52-a731-4665-a791-ee6479008805',
      menu_item_name: 'menu item name 2',
      sub_category_id: 111,
      description: 'description',
      price: 120,
      veg_egg_non: 'veg',
      packing_charges: 12,
      is_spicy: true,
      serves_how_many: 1,
      service_charges: 12,
      item_sgst_utgst: 0,
      item_cgst: 0,
      item_igst: 0,
      item_inclusive: true,
      disable: false,
      external_id: '123',
      allow_long_distance: true,
      next_available_after: '2022-04-27T04:54:01.883Z',
      is_deleted: false,
      variant_groups: [],
      addon_groups: [],
      menu_item_slots: null,
      quantity: 1,
      total_tax: 0,
      total_cost_without_tax: 134.4,
      in_stock: true,
      image: {},
    },
  ],
  menu_items_count: 1,
  delivery_time: 47,
  restaurant_details: {
    availability: {
      is_holiday: false,
      is_open: true,
    },
    restaurant_id: 'b0909e52-a731-4665-a791-ee6479008805',
    restaurant_name: 'Burger King',
    restaurant_status: 'active',
    like_count: 100000,
    like_count_label: '100.0K',
    rating: 0, //! BACKWARD_COMPATIBLE
  },
  invoice_breakout: {
    // subtotal: 88,
    total_tax: 0,
    // packing_charges: 0,
    // total: 147,
    // delivery_tip: 0,
    delivery_charges: 59,
    // offer_discount: 0,
  },
  cart_status: true,
};

export const postPlaceOrderResponse = {
  cancellation_policy: {
    terms_conditions: 'https://www.speedyy.com/terms-conditions/',
    note: 'If you cancel within 60 seconds of placing your order, a 100% refund will be issued. No refund for cancellation made after 60 seconds.',
  },
  customer_details: {
    full_name: 'Mohit Gupta',
    phone: '+918591114112',
    email: 'mohit.g@speedyy.com',
    alternate_phone: '+919819999999',
    customer_id: '33c6fdbc-8df6-4541-9d3f-f9e5ba4c0242',
    customer_device_id: '12412423432424413213123',
    customer_address_id: 'bd7e895f-0f7d-4dbe-9408-285abf5986ce',
    customer_addresses: [delivery_address],
    delivery_address: delivery_address,
  },
  order_id: 'a071b85f-5033-4bcb-a272-03d62e71eb87',
  order_acceptance_status: 'pending',
  delivery_status: 'pending',
  order_status: 'pending',
  payment_details: {
    id: '',
    payment_status: 'pending',
    transaction_token: 'caaea734a6f74e0d8812ca89d6868f401653376383820',
  },
  order_created_at: '2022-05-24T11:39:32.552Z',
  any_special_request: 'Dont ring door bell',
  menu_items_available: true,
  menu_items: [
    {
      menu_item_id: 11101,
      restaurant_id: 'b0909e52-a731-4665-a791-ee6479008805',
      menu_item_name: 'Veg Burger',
      sub_category_id: 111,
      description: 'description',
      price: 100,
      veg_egg_non: 'veg',
      packing_charges: 10,
      is_spicy: true,
      serves_how_many: 1,
      service_charges: 10,
      item_sgst_utgst: 0,
      item_cgst: 0,
      item_igst: 0,
      item_inclusive: true,
      disable: false,
      image: {},
      external_id: '123',
      allow_long_distance: true,
      next_available_after: '2022-04-27T04:54:01.883Z',
      is_deleted: false,
      variant_groups: [
        {
          variant_group_id: 98,
          variant_group_name: 'menu item 1 variant 1',
          variants: [
            {
              variant_id: 998,
              variant_group_id: 98,
              variant_name: 'variant group 1 variant name',
              is_default: true,
              price: 10,
              veg_egg_non: 'veg',
              in_stock: true,
              serves_how_many: 1,
              is_selected: true,
            },
          ],
          is_selected: true,
        },
        {
          variant_group_id: 99,
          variant_group_name: 'menu item 1 variant 2',
          variants: [
            {
              variant_id: 999,
              variant_group_id: 99,
              variant_name: 'variant group 1 variant name',
              is_default: true,
              price: 10,
              veg_egg_non: 'veg',
              in_stock: true,
              serves_how_many: 1,
              is_selected: true,
            },
          ],
          is_selected: true,
        },
      ],
      addon_groups: [
        {
          addon_group_id: 77,
          addon_group_name: 'addon group name',
          min_limit: 2,
          max_limit: 3,
          free_limit: 1,
          sequence: 1,
          addons: [
            {
              addon_id: 7768,
              addon_name: 'addon name 2',
              sequence: 1,
              price: 10,
              veg_egg_non: 'veg',
              in_stock: true,
              sgst_rate: 0,
              cgst_rate: 0,
              igst_rate: 0,
              gst_inclusive: true,
              external_id: '76778',
              is_selected: true,
            },
            {
              addon_id: 7769,
              addon_name: 'addon name 3',
              sequence: 1,
              price: 10,
              veg_egg_non: 'veg',
              in_stock: true,
              sgst_rate: 0,
              cgst_rate: 0,
              igst_rate: 0,
              gst_inclusive: true,
              external_id: '76779',
              is_selected: false,
            },
            {
              addon_id: 7767,
              addon_name: 'addon name 1',
              sequence: 1,
              price: 12,
              veg_egg_non: 'veg',
              in_stock: true,
              sgst_rate: 0,
              cgst_rate: 0,
              igst_rate: 0,
              gst_inclusive: true,
              external_id: '76777',
              is_selected: true,
            },
          ],
          is_selected: true,
        },
      ],
      menu_item_slots: null,
      quantity: 1,
      variants_total_cost_without_tax: 20,
      variants_instock: true,
      variants_count: 2,
      addons_total_cost_without_tax: 22,
      addons_total_tax: 0,
      addons_instock: true,
      addons_count: 2,
      total_tax: 0,
      total_cost_without_tax: 152,
      in_stock: true,
    },
  ],
  menu_items_count: 1,
  delivery_time: 47,
  restaurant_details: {
    availability: {
      is_holiday: false,
      is_open: true,
    },
    restaurant_id: 'b0909e52-a731-4665-a791-ee6479008805',
    restaurant_name: 'Burger King',
    restaurant_status: 'active',
    like_count: 100000,
    like_count_label: '100.0K',
    rating: 0, //! BACKWARD_COMPATIBLE
  },
  invoice_breakout: {
    // subtotal: 152,
    total_tax: 0,
    // packing_charges: 0,
    // total: 211,
    // delivery_tip: 0,
    delivery_charges: 59,
    // offer_discount: 0,
  },
};

export const language_response = [
  {
    id: '77206d74-8f7c-45b6-af7a-fe8901eb65ac',
    name: 'Hindi',
    status: 'active-inactive',
  },
  {
    id: 'a4a3cd49-1bdd-40ba-bd03-fa5bbbb15ab9',
    name: 'English',
    status: 'active',
  },
  {
    id: 'c2601f23-1df9-47bf-93ed-ec54c8b40998',
    name: 'Marathi',
    status: 'active',
  },
  {
    id: '8bb3f594-0953-4e3d-86f2-f9f75e671b89',
    name: 'Gujrati',
    status: 'active',
  },
  {
    id: '330a4101-e9bd-4d09-8f46-6251f4541769',
    name: 'French',
    status: 'inactive',
  },
  {
    id: '41f22c15-c372-45a0-ab8a-130ed999c2f0',
    name: 'German',
    status: 'inactive',
  },
  {
    id: '6970cfe9-3679-434c-b207-42d597cb56b2',
    name: 'Italian',
    status: 'inactive',
  },
];

export const getOrderDetailsAsVendor = {
  records: [
    {
      any_special_request: 'Dont ring door bell',
      coupon_id: null,
      created_at: '2022-05-12T14:27:22.518Z',
      customer_address: {
        apartment_road_area: 'apartment_road_area.',
        city: 'Mumbai',
        country: 'India',
        created_at: '2022-02-24T06:25:22.096Z',
        customer_id: '33c6fdbc-8df6-4541-9d3f-f9e5ba4c0242',
        directions: 'ABC',
        house_flat_block_no: 'HouseNumber,Wing,Block Number,',
        id: 'bd7e895f-0f7d-4dbe-9408-285abf5986ce',
        is_serviceable: true,
        latitude: 19.158672,
        longitude: 72.89071,
        name: 'Mohit',
        pincode: '0',
        state: 'Maharashtra',
        updated_at: '2022-02-24T06:25:22.096Z',
      },
      customer_device_id: '12412423432424413213123',
      customer_id: '17586cf0-75ac-4c92-a14d-3dfe174fe081',
      delivery_charges: 0,
      delivery_status: 'pending',
      delivery_time: 48,
      delivery_tip: 0,
      offer_discount: 0,
      order_acceptance_status: 'pending',
      order_id: 1,
      order_items: [
        {
          allow_long_distance: true,
          description: 'desc',
          external_id: '989',
          image: {},
          is_spicy: true,
          item_cgst: 0,
          item_igst: 0,
          item_inclusive: true,
          item_sgst_utgst: 0,
          name: 'menu item order name',
          order_addons: [
            {
              addon_group_id: 77,
              addon_group_name: 'addon group name',
              addon_id: 7767,
              addon_name: 'addon name',
              cgst_rate: 0,
              created_at: '2022-04-27T04:54:01.883+00:00',
              external_id: '123',
              gst_inclusive: false,
              igst_rate: 0,
              order_id: 1,
              order_item_id: 1,
              price: 10,
              sequence: 1,
              sgst_rate: 0,
              updated_at: '2022-04-27T04:54:01.883+00:00',
              veg_egg_non: 'veg',
            },
          ],
          order_id: 1,
          order_item_id: 1,
          order_variants: [
            {
              created_at: '2022-04-27T04:54:01.883+00:00',
              is_default: true,
              order_id: 1,
              order_item_id: 1,
              price: 10,
              serves_how_many: 1,
              updated_at: '2022-04-27T04:54:01.883+00:00',
              variant_group_id: 98,
              variant_group_name: 'variant group name',
              variant_id: 998,
              variant_name: 'variant name',
              veg_egg_non: 'veg',
            },
          ],
          packing_charges: 1,
          price: 100,
          quantity: 1,
          restaurant_id: 'b0909e52-a731-4665-a791-ee6479008805',
          serves_how_many: 1,
          service_charges: 0,
          sub_category_id: 11,
          veg_egg_non: 'veg',
        },
      ],
      vote_type: 0,
      order_rating: 0, //! BACKWARD_COMPATIBLE
      order_status: 'pending',
      packing_charges: 0,
      restaurant_id: 'b0909e52-a731-4665-a791-ee6479008805',
      total_customer_payable: 238.22,
      total_tax: 0.12,
      updated_at: '2022-05-12T14:27:22.518Z',
    },
  ],
};

export const getOrderDetailsAsAdmin = {
  records: [
    {
      any_special_request: 'Dont ring door bell',
      coupon_id: null,
      created_at: '2022-05-12T14:27:22.518Z',
      customer_address: {
        apartment_road_area: 'apartment_road_area.',
        city: 'Mumbai',
        country: 'India',
        created_at: '2022-02-24T06:25:22.096Z',
        customer_id: '33c6fdbc-8df6-4541-9d3f-f9e5ba4c0242',
        directions: 'ABC',
        house_flat_block_no: 'HouseNumber,Wing,Block Number,',
        id: 'bd7e895f-0f7d-4dbe-9408-285abf5986ce',
        is_serviceable: true,
        latitude: 19.158672,
        longitude: 72.89071,
        name: 'Mohit',
        pincode: '0',
        state: 'Maharashtra',
        updated_at: '2022-02-24T06:25:22.096Z',
      },
      customer_device_id: '12412423432424413213123',
      customer_id: '17586cf0-75ac-4c92-a14d-3dfe174fe081',
      delivery_charges: 0,
      delivery_status: 'pending',
      delivery_time: 48,
      delivery_tip: 0,
      offer_discount: 0,
      order_acceptance_status: 'pending',
      order_id: 1,
      order_items: [
        {
          allow_long_distance: true,
          description: 'desc',
          external_id: '989',
          image: {},
          is_spicy: true,
          item_cgst: 0,
          item_igst: 0,
          item_inclusive: true,
          item_sgst_utgst: 0,
          name: 'menu item order name',
          order_addons: [
            {
              addon_group_id: 77,
              addon_group_name: 'addon group name',
              addon_id: 7767,
              addon_name: 'addon name',
              cgst_rate: 0,
              created_at: '2022-04-27T04:54:01.883+00:00',
              external_id: '123',
              gst_inclusive: false,
              igst_rate: 0,
              order_id: 1,
              order_item_id: 1,
              price: 10,
              sequence: 1,
              sgst_rate: 0,
              updated_at: '2022-04-27T04:54:01.883+00:00',
              veg_egg_non: 'veg',
            },
          ],
          order_id: 1,
          order_item_id: 1,
          order_variants: [
            {
              created_at: '2022-04-27T04:54:01.883+00:00',
              is_default: true,
              order_id: 1,
              order_item_id: 1,
              price: 10,
              serves_how_many: 1,
              updated_at: '2022-04-27T04:54:01.883+00:00',
              variant_group_id: 98,
              variant_group_name: 'variant group name',
              variant_id: 998,
              variant_name: 'variant name',
              veg_egg_non: 'veg',
            },
          ],
          packing_charges: 1,
          price: 100,
          quantity: 1,
          restaurant_id: 'b0909e52-a731-4665-a791-ee6479008805',
          serves_how_many: 1,
          service_charges: 0,
          sub_category_id: 11,
          veg_egg_non: 'veg',
        },
      ],
      vote_type: 0,
      order_rating: 0, //! BACKWARD_COMPATIBLE
      order_status: 'pending',
      packing_charges: 0,
      payment_details: [
        {
          additional_details: {
            bankName: 'WALLET',
            bankTxnId: '187357186285',
            refundAmt: '0.00',
            resultInfo: {
              resultCode: '01',
              resultMsg: 'Txn Success',
              resultStatus: 'TXN_SUCCESS',
            },
            txnDate: '2022-05-18 15:28:37.0',
            txnType: 'SALE',
          },
          amount: 1,
          created_at: '2022-05-12T14:27:22.518718+00:00',
          customer_id: '33c6fdbc-8df6-4541-9d3f-f9e5ba4c0242',
          payment_gateway: 'WALLET',
          payment_id: 1,
          payment_method: 'PPI',
          payment_order_id: 1,
          payment_status: 'completed',
          transaction_id: '20220518111212800110168531851371782',
          transaction_token: '55938d4f422145838c626d26428896d21652365642957',
          updated_at: '2022-05-12T14:27:22.518718+00:00',
        },
        {
          additional_details: null,
          amount: null,
          created_at: '2022-05-20T13:08:22.993086+00:00',
          customer_id: '33c6fdbc-8df6-4541-9d3f-f9e5ba4c0242',
          payment_gateway: null,
          payment_id: 2,
          payment_method: null,
          payment_order_id: 1,
          payment_status: 'pending',
          transaction_id: null,
          transaction_token: '105088c5839945c2a70a6449dbfb1a671653052103420',
          updated_at: '2022-05-20T13:08:22.993086+00:00',
        },
        {
          additional_details: null,
          amount: null,
          created_at: '2022-05-20T13:08:22.993086+00:00',
          customer_id: '33c6fdbc-8df6-4541-9d3f-f9e5ba4c0242',
          payment_gateway: null,
          payment_id: 3,
          payment_method: null,
          payment_order_id: 1,
          payment_status: 'failed',
          transaction_id: null,
          transaction_token: '105088c5839945c2a70a6449dbfb1a671653052103420',
          updated_at: '2022-05-20T13:08:22.993086+00:00',
        },
      ],
      restaurant_id: 'b0909e52-a731-4665-a791-ee6479008805',
      total_customer_payable: 238.22,
      total_tax: 0.12,
      updated_at: '2022-05-12T14:27:22.518Z',
    },
  ],
};

export const get_cuisine_partner_response = [
  {
    id: 'acb0b0e4-dbcc-4688-8b1c-d79dfdabaf93',
    name: 'Chinese',
    status: 'active',
    image: {
      url: null,
    },
  },
  {
    id: '427140b8-cecc-4690-bec8-1255ae771bc4',
    name: 'Afghan',
    status: 'active',
    image: {
      url: null,
    },
  },
  {
    id: 'cd63888e-5dc5-4b47-9b9f-57a48e0fe769',
    name: 'Vietnamese',
    status: 'active',
    image: {
      url: null,
    },
  },
  {
    id: 'b536344a-482b-4c3b-9694-d0b1bea50bc9',
    name: 'Balkan',
    status: 'active',
    image: {
      url: null,
    },
  },
  {
    id: 'faad6b3e-f786-4325-9a64-ce0f4d240959',
    name: 'Italian - Pizza',
    status: 'active',
    image: {
      url: null,
    },
  },
  {
    id: '065b32fb-2264-4393-8e5b-f862e1a3a695',
    name: 'Middle Eastern',
    status: 'active',
    image: {
      url: null,
    },
  },
  {
    id: 'bafad85e-3f7f-496f-9851-6070275609e9',
    name: 'Burgers',
    status: 'active',
    image: {
      url: null,
    },
  },
  {
    id: '1340fdd1-e593-42af-b765-1badf590de16',
    name: 'Indian',
    status: 'active',
    image: {
      url: null,
    },
  },
  {
    id: '689432c3-3144-45c5-af65-107cf68facab',
    name: 'Japanese',
    status: 'active',
    image: {
      url: null,
    },
  },
  {
    id: '2f331b47-1230-4733-8afb-0e377f096023',
    name: 'German',
    status: 'active',
    image: {
      url: null,
    },
  },
  {
    id: '171e0d02-eafc-413b-be7a-ffc28624880f',
    name: 'Bar',
    status: 'active',
    image: {
      url: null,
    },
  },
  {
    id: 'b5af8efa-88f4-4993-aa34-eb149de8440b',
    name: 'Greek',
    status: 'active',
    image: {
      url: null,
    },
  },
];

export const get_cuisine_customer_response = [
  {
    id: 'acb0b0e4-dbcc-4688-8b1c-d79dfdabaf93',
    name: 'Chinese',
    status: 'active',
    image: {
      url: null,
    },
  },
  {
    id: '427140b8-cecc-4690-bec8-1255ae771bc4',
    name: 'Afghan',
    status: 'active',
    image: {
      url: null,
    },
  },
  {
    id: 'cd63888e-5dc5-4b47-9b9f-57a48e0fe769',
    name: 'Vietnamese',
    status: 'active',
    image: {
      url: null,
    },
  },
  {
    id: 'b536344a-482b-4c3b-9694-d0b1bea50bc9',
    name: 'Balkan',
    status: 'active',
    image: {
      url: null,
    },
  },
  {
    id: 'faad6b3e-f786-4325-9a64-ce0f4d240959',
    name: 'Italian - Pizza',
    status: 'active',
    image: {
      url: null,
    },
  },
  {
    id: '065b32fb-2264-4393-8e5b-f862e1a3a695',
    name: 'Middle Eastern',
    status: 'active',
    image: {
      url: null,
    },
  },
  {
    id: 'bafad85e-3f7f-496f-9851-6070275609e9',
    name: 'Burgers',
    status: 'active',
    image: {
      url: null,
    },
  },
  {
    id: '1340fdd1-e593-42af-b765-1badf590de16',
    name: 'Indian',
    status: 'active',
    image: {
      url: null,
    },
  },
  {
    id: '689432c3-3144-45c5-af65-107cf68facab',
    name: 'Japanese',
    status: 'active',
    image: {
      url: null,
    },
  },
  {
    id: '2f331b47-1230-4733-8afb-0e377f096023',
    name: 'German',
    status: 'active',
    image: {
      url: null,
    },
  },
  {
    id: '171e0d02-eafc-413b-be7a-ffc28624880f',
    name: 'Bar',
    status: 'active',
    image: {
      url: null,
    },
  },
  {
    id: 'b5af8efa-88f4-4993-aa34-eb149de8440b',
    name: 'Greek',
    status: 'active',
    image: {
      url: null,
    },
  },
];

export const get_city_admin_response = [
  {
    id: '542dfa07-21d6-41f2-ad5f-548cc7a020b6',
    name: 'Bangalore',
    status: 'active',
  },
  {
    id: 'd7aa9876-1ed0-4c47-831d-cf2e05d3fc91',
    name: 'Mumbai',
    status: 'active',
  },
  {
    id: 'b4c49e14-0b24-4dc2-b152-7074d7489ec6',
    name: 'Nagpur',
    status: 'active',
  },
  {
    id: 'b2d14d2e-ae34-4612-b99b-907aca3fe8f1',
    name: 'Thane',
    status: 'active',
  },
  {
    id: '4864a8d7-d1ac-4594-941a-f9b56f0fd920',
    name: 'Pimpri-Chinchwad',
    status: 'active',
  },
  {
    id: '5a1b8f12-0534-43cc-8d96-c3f01ca85a22',
    name: 'Nashik',
    status: 'active',
  },
  {
    id: 'f31a199f-7c67-4cfa-aedc-19ce55354502',
    name: 'Kalyan-Dombivli',
    status: 'active',
  },
  {
    id: '6a0ea048-f246-49aa-a76d-e365aae67a23',
    name: 'Vasai-Virar City MC',
    status: 'active',
  },
  {
    id: '9bcd95ca-1467-4275-a39b-5a54cb18af7f',
    name: 'Aurangabad',
    status: 'active',
  },
  {
    id: '6c4bca03-751c-44c0-8b68-068e89766063',
    name: 'Navi Mumbai',
    status: 'active',
  },
  {
    id: 'e08f934b-5246-459c-97a4-178cd81172a9',
    name: 'Solapur',
    status: 'active',
  },
  {
    id: '9be66e99-9bcd-4205-b053-ef0e7327f6bb',
    name: 'Mira-Bhayandar',
    status: 'active',
  },
  {
    id: '2326fe25-8b34-4e9a-9553-61c29fa21474',
    name: 'Bhiwandi-Nizampur MC',
    status: 'active',
  },
  {
    id: '8bde1199-d73a-4e37-89ec-f0f5af833d62',
    name: 'Amravati',
    status: 'active',
  },
  {
    id: '7d433613-8a14-44d6-beae-343c3a10aa29',
    name: 'Nanded Waghala',
    status: 'active',
  },
  {
    id: 'e285988c-fcfd-484b-9733-b095ab26ab3e',
    name: 'Kolhapur',
    status: 'active',
  },
  {
    id: '39222eb7-fa39-42b9-8e05-956179ca64be',
    name: 'Ulhasnagar',
    status: 'active',
  },
  {
    id: 'aacbb2e4-1215-4b73-b420-243d3c8fc897',
    name: 'Sangli-Miraj-Kupwad',
    status: 'active',
  },
  {
    id: 'bc1d8b12-13aa-46d7-b9e8-f1b11e5b8046',
    name: 'Malegaon',
    status: 'active',
  },
  {
    id: 'ee1992f1-c9bd-40bd-8a81-c78b99262f3a',
    name: 'Jalgaon',
    status: 'active',
  },
  {
    id: '345a4b25-e647-4014-af48-a18c71abdce8',
    name: 'Akola',
    status: 'active',
  },
  {
    id: '1f2ea0cc-2934-478d-8fd2-e095948e3b37',
    name: 'Latur',
    status: 'active',
  },
  {
    id: '8a451715-6661-4262-8f46-f28ff724068b',
    name: 'Dhule',
    status: 'active',
  },
  {
    id: 'c6a54c28-4caf-4c47-89e9-aa379a885df9',
    name: 'Ahmednagar',
    status: 'active',
  },
  {
    id: '0d26c141-27a6-4261-88d1-3e72bb01c8af',
    name: 'Chandrapur',
    status: 'active',
  },
  {
    id: 'a1caeadb-3f59-422a-95e8-f0e2d9681460',
    name: 'Parbhani',
    status: 'active',
  },
  {
    id: '2683fa5e-f929-4f50-92d5-1f862708d134',
    name: 'Ichalkaranji',
    status: 'active',
  },
  {
    id: '31a00069-2b66-45ca-887a-3822ede42f41',
    name: 'Jalna',
    status: 'active',
  },
  {
    id: 'fac66f2c-b937-459e-9cdd-e9c51755f40f',
    name: 'Ambarnath',
    status: 'active',
  },
  {
    id: '38e4ff62-00ab-4f25-a42a-8f60afa87fa2',
    name: 'Bhusawal',
    status: 'active',
  },
  {
    id: '632adfa8-4909-4bef-9cba-234c040eb151',
    name: 'Panvel',
    status: 'active',
  },
  {
    id: '08cec64e-61b9-4646-aeca-7914cbcd3261',
    name: 'Badlapur',
    status: 'active',
  },
  {
    id: '9f12be4c-8647-4549-99b8-608cca946a9e',
    name: 'Beed',
    status: 'active',
  },
  {
    id: '051c570c-97c8-4337-a182-a5f08fdfb4e1',
    name: 'Gondia',
    status: 'active',
  },
  {
    id: '8dd2e8be-8702-404d-b5bc-4894b86b4d3f',
    name: 'Satara',
    status: 'active',
  },
  {
    id: 'c898259a-769c-41cc-83fd-e9ccef35119a',
    name: 'Barshi',
    status: 'active',
  },
  {
    id: 'd7b55c40-1463-468f-a4e8-b39eb9915e55',
    name: 'Yavatmal',
    status: 'active',
  },
  {
    id: '6045bd11-decd-4a63-ae8e-724848907538',
    name: 'Achalpur',
    status: 'active',
  },
  {
    id: '1c60f6ca-2065-4606-9b84-48f3916e3c95',
    name: 'Osmanabad',
    status: 'active',
  },
  {
    id: '3537fc84-4df8-466b-9014-797765aef63f',
    name: 'Nandurbar',
    status: 'active',
  },
  {
    id: 'ada23b1b-2560-4b96-941d-e37ac0d4ef60',
    name: 'Wardha',
    status: 'active',
  },
  {
    id: 'c93e3a80-b592-4edd-b96e-7093264a46e2',
    name: 'Hinganghat',
    status: 'active',
  },
  {
    id: 'ecec96d0-eb04-4507-874b-3fbe56395814',
    name: 'Delhi',
    status: 'active',
  },
  {
    id: '15971528-ae60-4622-90c9-02b5d49d3fc3',
    name: 'Mumbai-suburban',
    status: 'active',
  },
  {
    id: 'af5d8a0f-8619-4f3f-82ec-b2b30a2332a6',
    name: 'Bhavnagar',
    status: 'active',
  },
  {
    id: '59da6e3b-4e74-47ab-b350-1a26eb6a9501',
    name: 'Pune',
    status: 'active',
  },
  {
    id: '51ad1f92-e54a-4f2a-8452-d68cdd7e3a7b',
    name: 'Ahmedabad',
    status: 'active',
  },
];

export const get_city_partner_response = [
  {id: '542dfa07-21d6-41f2-ad5f-548cc7a020b6', name: 'Bangalore'},
  {id: 'd7aa9876-1ed0-4c47-831d-cf2e05d3fc91', name: 'Mumbai'},
  {id: 'b4c49e14-0b24-4dc2-b152-7074d7489ec6', name: 'Nagpur'},
  {id: 'b2d14d2e-ae34-4612-b99b-907aca3fe8f1', name: 'Thane'},
  {
    id: '4864a8d7-d1ac-4594-941a-f9b56f0fd920',
    name: 'Pimpri-Chinchwad',
  },
  {id: '5a1b8f12-0534-43cc-8d96-c3f01ca85a22', name: 'Nashik'},
  {
    id: 'f31a199f-7c67-4cfa-aedc-19ce55354502',
    name: 'Kalyan-Dombivli',
  },
  {
    id: '6a0ea048-f246-49aa-a76d-e365aae67a23',
    name: 'Vasai-Virar City MC',
  },
  {id: '9bcd95ca-1467-4275-a39b-5a54cb18af7f', name: 'Aurangabad'},
  {id: '6c4bca03-751c-44c0-8b68-068e89766063', name: 'Navi Mumbai'},
  {id: 'e08f934b-5246-459c-97a4-178cd81172a9', name: 'Solapur'},
  {
    id: '9be66e99-9bcd-4205-b053-ef0e7327f6bb',
    name: 'Mira-Bhayandar',
  },
  {
    id: '2326fe25-8b34-4e9a-9553-61c29fa21474',
    name: 'Bhiwandi-Nizampur MC',
  },
  {id: '8bde1199-d73a-4e37-89ec-f0f5af833d62', name: 'Amravati'},
  {
    id: '7d433613-8a14-44d6-beae-343c3a10aa29',
    name: 'Nanded Waghala',
  },
  {id: 'e285988c-fcfd-484b-9733-b095ab26ab3e', name: 'Kolhapur'},
  {id: '39222eb7-fa39-42b9-8e05-956179ca64be', name: 'Ulhasnagar'},
  {
    id: 'aacbb2e4-1215-4b73-b420-243d3c8fc897',
    name: 'Sangli-Miraj-Kupwad',
  },
  {id: 'bc1d8b12-13aa-46d7-b9e8-f1b11e5b8046', name: 'Malegaon'},
  {id: 'ee1992f1-c9bd-40bd-8a81-c78b99262f3a', name: 'Jalgaon'},
  {id: '345a4b25-e647-4014-af48-a18c71abdce8', name: 'Akola'},
  {id: '1f2ea0cc-2934-478d-8fd2-e095948e3b37', name: 'Latur'},
  {id: '8a451715-6661-4262-8f46-f28ff724068b', name: 'Dhule'},
  {id: 'c6a54c28-4caf-4c47-89e9-aa379a885df9', name: 'Ahmednagar'},
  {id: '0d26c141-27a6-4261-88d1-3e72bb01c8af', name: 'Chandrapur'},
  {id: 'a1caeadb-3f59-422a-95e8-f0e2d9681460', name: 'Parbhani'},
  {
    id: '2683fa5e-f929-4f50-92d5-1f862708d134',
    name: 'Ichalkaranji',
  },
  {id: '31a00069-2b66-45ca-887a-3822ede42f41', name: 'Jalna'},
  {id: 'fac66f2c-b937-459e-9cdd-e9c51755f40f', name: 'Ambarnath'},
  {id: '38e4ff62-00ab-4f25-a42a-8f60afa87fa2', name: 'Bhusawal'},
  {id: '632adfa8-4909-4bef-9cba-234c040eb151', name: 'Panvel'},
  {id: '08cec64e-61b9-4646-aeca-7914cbcd3261', name: 'Badlapur'},
  {id: '9f12be4c-8647-4549-99b8-608cca946a9e', name: 'Beed'},
  {id: '051c570c-97c8-4337-a182-a5f08fdfb4e1', name: 'Gondia'},
  {id: '8dd2e8be-8702-404d-b5bc-4894b86b4d3f', name: 'Satara'},
  {id: 'c898259a-769c-41cc-83fd-e9ccef35119a', name: 'Barshi'},
  {id: 'd7b55c40-1463-468f-a4e8-b39eb9915e55', name: 'Yavatmal'},
  {id: '6045bd11-decd-4a63-ae8e-724848907538', name: 'Achalpur'},
  {id: '1c60f6ca-2065-4606-9b84-48f3916e3c95', name: 'Osmanabad'},
  {id: '3537fc84-4df8-466b-9014-797765aef63f', name: 'Nandurbar'},
  {id: 'ada23b1b-2560-4b96-941d-e37ac0d4ef60', name: 'Wardha'},
  {id: 'c93e3a80-b592-4edd-b96e-7093264a46e2', name: 'Hinganghat'},
  {id: 'ecec96d0-eb04-4507-874b-3fbe56395814', name: 'Delhi'},
  {
    id: '15971528-ae60-4622-90c9-02b5d49d3fc3',
    name: 'Mumbai-suburban',
  },
  {id: 'af5d8a0f-8619-4f3f-82ec-b2b30a2332a6', name: 'Bhavnagar'},
  {id: '59da6e3b-4e74-47ab-b350-1a26eb6a9501', name: 'Pune'},
  {id: '51ad1f92-e54a-4f2a-8452-d68cdd7e3a7b', name: 'Ahmedabad'},
];

const start_time = new Date();
start_time.setMinutes(start_time.getMinutes() + 3);
//const five_minutes = start_time.getTime();
//const five_minutes = Math.floor(start_time.getTime() / 1000);

export const cashfree_placed_order = {
  status: true,
  statusCode: 200,
  message: 'Successful Response',
  result: {
    order_id: 979,
    order_acceptance_status: 'pending',
    delivery_status: 'pending',
    order_status: 'pending',
    order_created_at: '2022-08-22T05:58:16.570Z',
    payment_details: {
      id: '692bf84b-43ed-4597-a399-3e1ead75f360',
      payment_status: 'completed',
      transaction_token: 'UZaMtgQrNYww6XsGENRr',
    },
    customer_details: {
      full_name: 'Jay',
      phone: '+917972210040',
      email: 'jay.b@speedyy.com',
      alternate_phone: null,
      customer_id: 'fc9a30a8-713e-44c4-8d0e-8a2bbb5be08b',
      customer_device_id: '12412423432424413213123',
      customer_address_id: 'e512c168-9bce-460b-bd50-7d809c31cdb3',
      customer_addresses: [
        {
          id: 'e512c168-9bce-460b-bd50-7d809c31cdb3',
          customer_id: 'fc9a30a8-713e-44c4-8d0e-8a2bbb5be08b',
          name: 'Gatewayofindia',
          house_flat_block_no: 'a',
          apartment_road_area: 'a',
          pincode: '400001',
          directions: null,
          longitude: 72.83465422689915,
          latitude: 18.92198402356665,
          city: 'Mumbai',
          state: 'Maharashtra',
          country: 'India',
          created_at: '2022-08-21T07:01:54.157Z',
          updated_at: '2022-08-21T07:01:54.157Z',
          is_serviceable: true,
          delivery_details: {
            serviceability: true,
            delivery_cost: 30,
            serviceable: true,
          },
          customer_name: 'Jay',
          phone: '+917972210040',
          email: 'jay.b@speedyy.com',
          alternate_phone: null,
        },
      ],
      delivery_address: {
        id: 'e512c168-9bce-460b-bd50-7d809c31cdb3',
        customer_id: 'fc9a30a8-713e-44c4-8d0e-8a2bbb5be08b',
        name: 'Gatewayofindia',
        house_flat_block_no: 'a',
        apartment_road_area: 'a',
        pincode: '400001',
        directions: null,
        longitude: 72.83465422689915,
        latitude: 18.92198402356665,
        city: 'Mumbai',
        state: 'Maharashtra',
        country: 'India',
        created_at: '2022-08-21T07:01:54.157Z',
        updated_at: '2022-08-21T07:01:54.157Z',
        is_serviceable: true,
        delivery_details: {
          serviceability: true,
          delivery_cost: 30,
          serviceable: true,
        },
        customer_name: 'Jay',
        phone: '+917972210040',
        email: 'jay.b@speedyy.com',
        alternate_phone: null,
      },
    },
    any_special_request: 'Dont ring door bell',
    menu_items_available: true,
    menu_items: [
      {
        menu_item_id: 13490,
        restaurant_id: '09668cc2-18f8-4150-8377-99630e63aa08',
        menu_item_name: 'Ginger-Garlic Bread',
        sub_category_id: 1099,
        description: 'Ginger-Garlic Bread',
        price: 200,
        veg_egg_non: 'veg',
        packing_charges: 0,
        is_spicy: false,
        serves_how_many: 1,
        service_charges: 5,
        item_sgst_utgst: 0,
        item_cgst: 0,
        item_igst: 0,
        item_inclusive: true,
        disable: false,
        image: {
          name: 'be11d432-8865-4d8c-ab2c-5144c57cc612.jpeg',
          path: 'menu_item/images/',
          bucket: 'speedyy-dev-core-api-public',
        },
        external_id: 'ght-128978912bkj129',
        allow_long_distance: true,
        next_available_after: null,
        is_deleted: false,
        variant_groups: [],
        addon_groups: [],
        menu_item_slots: null,
        quantity: 1,
        total_tax: 0,
        total_cost_without_tax: 210,
        in_stock: true,
      },
    ],
    menu_items_count: 1,
    delivery_time: 0,
    restaurant_details: {
      restaurant_id: '09668cc2-18f8-4150-8377-99630e63aa08',
      restaurant_name: 'Backend-Restaurant',
      restaurant_status: 'active',
      like_count: 0,
      like_count_label: '0',
      rating: 0, //! BACKWARD_COMPATIBLE
      availability: {
        is_holiday: false,
        is_open: true,
        closing_at: '2022-08-22T17:30:00.000Z',
      },
      latitude: 18.953316,
      longitude: 72.80107,
    },
    invoice_breakout: {
      menu_items: [
        {
          item_name: 'Ginger-Garlic Bread',
          item_quantity: 1,
          item_cgst: 0,
          item_sgst: 0,
          item_igst: 0,
          item_price: 200,
          total_item_amount: 200,
          item_tax_amount: 0,
          item_packing_charges: 0,
          addon_groups: [],
          variants: [],
          total_variant_cost: 0,
          total_addon_group_price: 0,
          total_addon_group_tax_amount: 0,
          total_individual_food_item_cost: 200,
          total_individual_food_item_tax: 0,
        },
      ],
      order_packing_charge: 0,
      total_food_cost: 200,
      total_packing_charges: 0,
      total_tax: 0,
      delivery_charges: 30,
      transaction_charges_rate: 3,
      transaction_charges: 6.9,
      total_customer_payable: 236.9,
      // refundable_amount: 200,
      vendor_payout_amount: 200,
      description: {
        menu_items: {
          item_id: 'Menu Itm Id from database',
          item_name: 'Menu Item Name from fatabase',
          item_quantity: 'Menu Item Quantity selected by customer',
          item_cgst: 'Menu Item CGST Tax Rate from database',
          item_sgst: 'Menu Item SGST Tax Rate from database',
          item_igst: 'Menu Item IGST Tax Rate from database',
          item_price: 'Menu Item Price from database',
          variants: {
            desc: 'List of all Variant group with choosed variants',
            variant_group_id: 'Variant Group Id from database',
            variant_group_name: 'Variant Group Name from database',
            variant_id: 'Variant Id from database',
            variant_name: 'Variant Name from database',
            variant_price: 'Variant Price from database',
          },
          total_variant_cost: 'Sum Of all variant_price of from variants array',
          addon_groups: {
            addon_group_id: 'Addon Group Id from database',
            addon_group_name: 'Addon Group Name from database',
            addons: {
              desc: 'List of all Addons selected',
              addon_id: 'Addon Id from database',
              addon_name: 'Addon Name from database',
              addon_cgst: 'Addon CGST Tax Rate from database',
              addon_sgst: 'Addon SGST Tax Rate from database',
              addon_igst: 'Addon IGST Tax Rate from database',
              addon_price: 'Addon Price from database',
              addon_tax_amount:
                'Calculated Tax value from sum of taxes(IGST+CGST+SGST) and applied on addon_price\n  >>> (addon_price / 100)*(addon_cgst+addon_sgst+addon_igst)',
            },
            free_limit: '',
            total_addon_price: 'Sum Of all addon_price of from addons array',
            total_addon_tax_amount:
              'Sum Of all addon_tax_amount of from addons array',
          },
          total_addon_group_price:
            '(Sum Of all total_addon_price of from addon_groups array) * item_quantity',
          total_addon_group_tax_amount:
            'Sum Of all total_addon_tax_amount of from addon_groups array',
          total_item_amount:
            'Calculated Value from adding all selected variants price on top of Menu Item Price\n  >>> ((item_price + total_variant_cost) * item_quantity)',
          item_tax_amount:
            'Calculated Value of tax applied on food amount if tax is not inclusive\n  >>> ((total_item_amount / 100) * (item_cgst + item_sgst + item_igst))',
          item_packing_charges:
            'Packing charges of Menu Item if set by restaurant',
          total_individual_food_item_cost:
            ' Total Item Cost (including item cost with variant cost and addons cost)\n  >>> total_item_amount + total_addon_group_price',
          total_individual_food_item_tax:
            'Total Item Tax (including item tax with variant and addons tax)\n  >>> item_tax_amount + total_addon_group_tax_amount',
        },
        coupon_details: {
          coupon_id: 'Coupon Id from database',
          code: 'Coupon code from database',
          level: 'Coupon level from database',
          min_order_value_rupees: 'Coupon min_order_value_rupees from database',
          type: 'Coupon type from database',
          max_discount_rupees: 'Coupon max_discount_rupees from database',
          discount_percentage: 'Coupon discount_percentage from database',
          discount_amount_rupees: 'Coupon discount_amount_rupees from database',
          discount_share_percentage_vendor:
            'Coupon discount_share_percentage_vendor from database',
          discount_share_percentage_speedyy:
            'Coupon discount_share_percentage_speedyy from database',
          discount_amount_applied:
            'Applicable discount amount calculated based on Other values\n  ',
          discount_share_amount_vendor:
            'The Amount Bared by vendor calculated percentage of discount_amount_applied\n  >>>  (discount_amount_applied /100) * discount_share_percentage_vendor',
          discount_share_amount_speedyy:
            'Calculated Rest of the discount amount bared by speedyy\n  >>> discount_amount_applied - discount_share_amount_vendor',
        },
        payment_transaction_id:
          'Payment uuid when payment is made by customer and is verified',
        delivery_order_id: 'delivery order id when order is placed',
        payout_transaction_id:
          'Payout transaction ID when order payout processing started',
        order_packing_charge:
          'Packing Charges on full order if set by restaurant',
        total_food_cost:
          'Sum of all total_item_amount + total_addon_group_price',
        total_tax:
          'Sum of item_tax_amount and total_addon_group_tax_amount in menu_items array',
        total_packing_charges:
          'Sum of all item_packing_charges from menu_items and order_packing_charge',
        delivery_charges:
          'By delivery partner based on >>> total_food_cost + total_tax + total_packing_charges - discount_amount_applied',
        transaction_charges_rate: 'From .env: 3%',
        transaction_charges:
          'Calculated on\n  >>> ((total_food_cost + total_taxes + total_packing_charges - discount_amount_applied + delivery_charges) / 100 ) * transaction_charges_rate',
        total_customer_payable:
          'total_food_cost + total_taxes + total_packing_charges - discount_amount_applied + delivery_charges + transaction_charges',
        // refundable_amount:
        //   'total_food_cost + total_taxes - discount_amount_applied',
        vendor_payout_amount:
          'total_food_cost + total_taxes + total_packing_charges - discount_share_amount_vendor',
        version: '0.0.1',
      },
    },
  },
};

export const vendor_accepted_order = {
  id: 1125,
  restaurant_id: '09668cc2-18f8-4150-8377-99630e63aa08',
  customer_id: 'fc9a30a8-713e-44c4-8d0e-8a2bbb5be08b',
  customer_device_id: '12412423432424413213123',
  customer_address: {
    id: 'e512c168-9bce-460b-bd50-7d809c31cdb3',
    city: 'Mumbai',
    name: 'Gatewayofindia',
    email: 'jay.b@speedyy.com',
    phone: '+917972210040',
    state: 'Maharashtra',
    country: 'India',
    pincode: '400001',
    latitude: 12.937814,
    longitude: 77.614576,
    created_at: '2022-08-21T07:01:54.157Z',
    directions: null,
    updated_at: '2022-08-21T07:01:54.157Z',
    customer_id: 'fc9a30a8-713e-44c4-8d0e-8a2bbb5be08b',
    deliverable: true,
    customer_name: 'Jay',
    alternate_phone: null,
    delivery_details: {
      drop_eta: 10,
      pickup_eta: 10,
      deliverable: true,
      delivery_cost: 58,
    },
    apartment_road_area: 'a',
    house_flat_block_no: 'a',
  },
  order_delivered_at: null,
  delivery_status: 'pending',
  delivery_details: null,
  delivery_charges: 58,
  delivery_tip: null,
  order_status: 'placed',
  order_acceptance_status: 'accepted',
  total_customer_payable: 265.74,
  total_tax: 0,
  packing_charges: 0,
  offer_discount: null,
  coupon_id: null,
  vote_type: 0,
  order_rating: 0, //! BACKWARD_COMPATIBLE
  any_special_request: 'Dont ring door bell',
  cancelled_by: null,
  cancellation_details: null,
  cancellation_time: null,
  cancellation_user_id: null,
  created_at: '2022-09-15T07:14:56.445Z',
  updated_at: '2022-09-15T07:16:08.695Z',
  delivery_order_id: '20732679',
  pickup_eta: 10,
  drop_eta: 30,
  order_placed_time: '2022-09-15T07:15:42.332Z',
  vendor_accepted_time: '2022-09-15T07:16:07.127Z',
  accepted_vendor_id: '23c5676c-ce35-4253-97b0-02db9bdac3d2',
  preparation_time: 10,
  vendor_ready_marked_time: null,
  payout_transaction_id: null,
  transaction_charges: 7.74,
  vendor_payout_amount: 200,
  invoice_breakout: {
    total_tax: 0,
    menu_items: [
      {
        variants: [],
        item_cgst: 0,
        item_igst: 0,
        item_name: 'Ginger-Garlic Bread',
        item_sgst: 0,
        item_price: 200,
        addon_groups: [],
        item_quantity: 1,
        item_tax_amount: 0,
        total_item_amount: 200,
        total_variant_cost: 0,
        item_packing_charges: 0,
        total_addon_group_price: 0,
        total_addon_group_tax_amount: 0,
        total_individual_food_item_tax: 0,
        total_individual_food_item_cost: 200,
      },
    ],
    description: {
      version: '0.0.1',
      total_tax:
        'Sum of item_tax_amount and total_addon_group_tax_amount in menu_items array',
      menu_items: {
        item_id: 'Menu Itm Id from database',
        variants: {
          desc: 'List of all Variant group with choosed variants',
          variant_id: 'Variant Id from database',
          variant_name: 'Variant Name from database',
          variant_price: 'Variant Price from database',
          variant_group_id: 'Variant Group Id from database',
          variant_group_name: 'Variant Group Name from database',
        },
        item_cgst: 'Menu Item CGST Tax Rate from database',
        item_igst: 'Menu Item IGST Tax Rate from database',
        item_name: 'Menu Item Name from fatabase',
        item_sgst: 'Menu Item SGST Tax Rate from database',
        item_price: 'Menu Item Price from database',
        addon_groups: {
          addons: {
            desc: 'List of all Addons selected',
            addon_id: 'Addon Id from database',
            addon_cgst: 'Addon CGST Tax Rate from database',
            addon_igst: 'Addon IGST Tax Rate from database',
            addon_name: 'Addon Name from database',
            addon_sgst: 'Addon SGST Tax Rate from database',
            addon_price: 'Addon Price from database',
            addon_tax_amount:
              'Calculated Tax value from sum of taxes(IGST+CGST+SGST) and applied on addon_price\n  >>> (addon_price / 100)*(addon_cgst+addon_sgst+addon_igst)',
          },
          free_limit: '',
          addon_group_id: 'Addon Group Id from database',
          addon_group_name: 'Addon Group Name from database',
          total_addon_price: 'Sum Of all addon_price of from addons array',
          total_addon_tax_amount:
            'Sum Of all addon_tax_amount of from addons array',
        },
        item_quantity: 'Menu Item Quantity selected by customer',
        item_tax_amount:
          'Calculated Value of tax applied on food amount if tax is not inclusive\n  >>> ((total_item_amount / 100) * (item_cgst + item_sgst + item_igst))',
        total_item_amount:
          'Calculated Value from adding all selected variants price on top of Menu Item Price\n  >>> ((item_price + total_variant_cost) * item_quantity)',
        total_variant_cost: 'Sum Of all variant_price of from variants array',
        item_packing_charges:
          'Packing charges of Menu Item if set by restaurant',
        total_addon_group_price:
          '(Sum Of all total_addon_price of from addon_groups array) * item_quantity',
        total_addon_group_tax_amount:
          'Sum Of all total_addon_tax_amount of from addon_groups array',
        total_individual_food_item_tax:
          'Total Item Tax (including item tax with variant and addons tax)\n  >>> item_tax_amount + total_addon_group_tax_amount',
        total_individual_food_item_cost:
          ' Total Item Cost (including item cost with variant cost and addons cost)\n  >>> total_item_amount + total_addon_group_price',
      },
      delivery_order_id: 'Delivery order id when order is placed',
      coupon_details: {
        code: 'Coupon code from database',
        type: 'Coupon type from database',
        level: 'Coupon level from database',
        coupon_id: 'Coupon Id from database',
        discount_percentage: 'Coupon discount_percentage from database',
        max_discount_rupees: 'Coupon max_discount_rupees from database',
        discount_amount_rupees: 'Coupon discount_amount_rupees from database',
        min_order_value_rupees: 'Coupon min_order_value_rupees from database',
        discount_amount_applied:
          'Applicable discount amount calculated based on Other values\n  ',
        discount_share_amount_vendor:
          'The Amount Bared by vendor calculated percentage of discount_amount_applied\n  >>>  (discount_amount_applied /100) * discount_share_percentage_vendor',
        discount_share_amount_speedyy:
          'Calculated Rest of the discount amount bared by speedyy\n  >>> discount_amount_applied - discount_share_amount_vendor',
        discount_share_percentage_vendor:
          'Coupon discount_share_percentage_vendor from database',
        discount_share_percentage_speedyy:
          'Coupon discount_share_percentage_speedyy from database',
      },
      total_food_cost: 'Sum of all total_item_amount + total_addon_group_price',
      delivery_charges:
        'By delivery partner based on >>> total_food_cost + total_tax + total_packing_charges - discount_amount_applied',
      refundable_amount:
        'total_food_cost + total_taxes - discount_amount_applied',
      transaction_charges:
        'Calculated on\n  >>> ((total_food_cost + total_taxes + total_packing_charges - discount_amount_applied + delivery_charges) / 100 ) * transaction_charges_rate',
      order_packing_charge:
        'Packing Charges on full order if set by restaurant',
      vendor_payout_amount:
        'total_food_cost + total_taxes + total_packing_charges - discount_share_amount_vendor',
      payout_transaction_id:
        'Payout transaction ID when order payout processing started',
      total_packing_charges:
        'Sum of all item_packing_charges from menu_items and order_packing_charge',
      payment_transaction_id:
        'Payment uuid when payment is made by customer and is verified',
      total_customer_payable:
        'total_food_cost + total_taxes + total_packing_charges - discount_amount_applied + delivery_charges + transaction_charges',
      transaction_charges_rate: 'From .env: 3%',
    },
    delivery_order_id: 20732679,
    total_food_cost: 200,
    delivery_charges: 58,
    transaction_charges: 7.74,
    order_packing_charge: 0,
    vendor_payout_amount: 200,
    total_packing_charges: 0,
    payment_transaction_id: '1254251',
    total_customer_payable: 265.74,
    transaction_charges_rate: 3,
    transaction_refund_charges: 7.74,
    vendor_cancellation_charges: 73.47999999999999,
    transaction_refund_charges_rate: 3,
  },
  stop_payment: false,
  order_pickedup_time: null,
  comments: null,
  reviewed_at: null,
  refund_status: null,
  additional_details: null,
};

export const orderDetails = {
  order_id: 1,
  restaurant_id: 'b0909e52-a731-4665-a791-ee6479008805',
  customer_id: '33c6fdbc-8df6-4541-9d3f-f9e5ba4c0242',
  customer_device_id: '12412423432424413213123',
  customer_address: {
    id: 'bd7e895f-0f7d-4dbe-9408-285abf5986ce',
    city: 'Mumbai',
    name: 'Mohit',
    email: 'mohit.g@speedyy.com',
    phone: '+918591114112',
    state: 'Maharashtra',
    country: 'India',
    pincode: '0',
    latitude: '19.158672',
    longitude: '72.89071',
    created_at: '2022-02-24T06:25:22.096Z',
    directions: 'ABC',
    updated_at: '2022-02-24T06:25:22.096Z',
    customer_id: '33c6fdbc-8df6-4541-9d3f-f9e5ba4c0242',
    deliverable: true,
    customer_name: 'Mohit Gupta',
    alternate_phone: '+919819999999',
    delivery_details: {
      drop_eta: 35,
      pickup_eta: 1,
      deliverable: true,
      delivery_cost: 59,
    },
    apartment_road_area: 'apartment_road_area.',
    house_flat_block_no: 'HouseNumber,Wing,Block Number,',
  },
  order_delivered_at: null,
  delivery_status: 'pending',
  delivery_charges: 59,
  delivery_tip: null,
  order_status: 'placed',
  order_acceptance_status: 'pending',
  total_customer_payable: 177.78,
  total_tax: 0,
  packing_charges: 0,
  offer_discount: 28.4,
  coupon_id: 20,
  vote_type: 0,
  order_rating: 0, //! BACKWARD_COMPATIBLE
  any_special_request: 'Dont ring door bell',
  cancelled_by: null,
  cancellation_details: null,
  cancellation_time: null,
  vendor_ready_marked_time: null,
  created_at: '2022-09-26T03:23:58.475Z',
  updated_at: '2022-09-26T03:23:58.493Z',
  delivery_order_id: null,
  pickup_eta: 1,
  drop_eta: 35,
  preparation_time: null,
  invoice_breakout: {
    total_tax: 0,
    menu_items: [
      {
        variants: [
          {
            variant_id: 998,
            variant_name: 'variant group 1 variant name',
            variant_price: 10,
            variant_group_id: 98,
            variant_group_name: 'menu item 1 variant 1',
          },
          {
            variant_id: 999,
            variant_name: 'variant group 1 variant name',
            variant_price: 10,
            variant_group_id: 99,
            variant_group_name: 'menu item 1 variant 2',
          },
        ],
        item_cgst: 0,
        item_igst: 0,
        item_name: 'Veg Burger',
        item_sgst: 0,
        item_price: 100,
        addon_groups: [
          {
            addons: [
              {
                addon_id: 7767,
                addon_cgst: 0,
                addon_igst: 0,
                addon_name: 'addon name 1',
                addon_sgst: 0,
                addon_price: 12,
                addon_tax_amount: 0,
              },
              {
                addon_id: 7768,
                addon_cgst: 0,
                addon_igst: 0,
                addon_name: 'addon name 2',
                addon_sgst: 0,
                addon_price: 10,
                addon_tax_amount: 0,
              },
            ],
            free_limit: 1,
            addon_group_id: 77,
            addon_group_name: 'addon group name',
            total_addon_price: 22,
            total_addon_tax_amount: 0,
          },
        ],
        item_quantity: 1,
        item_tax_amount: 0,
        total_item_amount: 120,
        total_variant_cost: 20,
        item_packing_charges: 0,
        total_addon_group_price: 22,
        total_addon_group_tax_amount: 0,
        total_individual_food_item_tax: 0,
        total_individual_food_item_cost: 142,
      },
    ],
    description: {
      version: '0.0.1',
      total_tax:
        'Sum of item_tax_amount and total_addon_group_tax_amount in menu_items array',
      menu_items: {
        item_id: 'Menu Itm Id from database',
        variants: {
          desc: 'List of all Variant group with choosed variants',
          variant_id: 'Variant Id from database',
          variant_name: 'Variant Name from database',
          variant_price: 'Variant Price from database',
          variant_group_id: 'Variant Group Id from database',
          variant_group_name: 'Variant Group Name from database',
        },
        item_cgst: 'Menu Item CGST Tax Rate from database',
        item_igst: 'Menu Item IGST Tax Rate from database',
        item_name: 'Menu Item Name from fatabase',
        item_sgst: 'Menu Item SGST Tax Rate from database',
        item_price: 'Menu Item Price from database',
        addon_groups: {
          addons: {
            desc: 'List of all Addons selected',
            addon_id: 'Addon Id from database',
            addon_cgst: 'Addon CGST Tax Rate from database',
            addon_igst: 'Addon IGST Tax Rate from database',
            addon_name: 'Addon Name from database',
            addon_sgst: 'Addon SGST Tax Rate from database',
            addon_price: 'Addon Price from database',
            addon_tax_amount:
              'Calculated Tax value from sum of taxes(IGST+CGST+SGST) and applied on addon_price\n  >>> (addon_price / 100)*(addon_cgst+addon_sgst+addon_igst)',
          },
          free_limit: '',
          addon_group_id: 'Addon Group Id from database',
          addon_group_name: 'Addon Group Name from database',
          total_addon_price: 'Sum Of all addon_price of from addons array',
          total_addon_tax_amount:
            'Sum Of all addon_tax_amount of from addons array',
        },
        item_quantity: 'Menu Item Quantity selected by customer',
        item_tax_amount:
          'Calculated Value of tax applied on food amount if tax is not inclusive\n  >>> ((total_item_amount / 100) * (item_cgst + item_sgst + item_igst))',
        total_item_amount:
          'Calculated Value from adding all selected variants price on top of Menu Item Price\n  >>> ((item_price + total_variant_cost) * item_quantity)',
        total_variant_cost: 'Sum Of all variant_price of from variants array',
        item_packing_charges:
          'Packing charges of Menu Item if set by restaurant',
        total_addon_group_price:
          '(Sum Of all total_addon_price of from addon_groups array) * item_quantity',
        total_addon_group_tax_amount:
          'Sum Of all total_addon_tax_amount of from addon_groups array',
        total_individual_food_item_tax:
          'Total Item Tax (including item tax with variant and addons tax)\n  >>> item_tax_amount + total_addon_group_tax_amount',
        total_individual_food_item_cost:
          ' Total Item Cost (including item cost with variant cost and addons cost)\n  >>> total_item_amount + total_addon_group_price',
      },
      delivery_order_id: 'Delivery order id when order is placed',
      coupon_details: {
        code: 'Coupon code from database',
        type: 'Coupon type from database',
        level: 'Coupon level from database',
        coupon_id: 'Coupon Id from database',
        discount_percentage: 'Coupon discount_percentage from database',
        max_discount_rupees: 'Coupon max_discount_rupees from database',
        discount_amount_rupees: 'Coupon discount_amount_rupees from database',
        min_order_value_rupees: 'Coupon min_order_value_rupees from database',
        discount_amount_applied:
          'Applicable discount amount calculated based on Other values\n  ',
        discount_share_amount_vendor:
          'The Amount Bared by vendor calculated percentage of discount_amount_applied\n  >>>  (discount_amount_applied /100) * discount_share_percentage_vendor',
        discount_share_amount_speedyy:
          'Calculated Rest of the discount amount bared by speedyy\n  >>> discount_amount_applied - discount_share_amount_vendor',
        discount_share_percentage_vendor:
          'Coupon discount_share_percentage_vendor from database',
        discount_share_percentage_speedyy:
          'Coupon discount_share_percentage_speedyy from database',
      },
      total_food_cost: 'Sum of all total_item_amount + total_addon_group_price',
      delivery_charges:
        'By delivery partner based on >>> total_food_cost + total_tax + total_packing_charges - discount_amount_applied',
      refundable_amount:
        'total_food_cost + total_taxes - discount_amount_applied',
      transaction_charges:
        'Calculated on\n  >>> ((total_food_cost + total_taxes + total_packing_charges - discount_amount_applied + delivery_charges) / 100 ) * transaction_charges_rate',
      order_packing_charge:
        'Packing Charges on full order if set by restaurant',
      vendor_payout_amount:
        'total_food_cost + total_taxes + total_packing_charges - discount_share_amount_vendor',
      payout_transaction_id:
        'Payout transaction ID when order payout processing started',
      total_packing_charges:
        'Sum of all item_packing_charges from menu_items and order_packing_charge',
      payment_transaction_id:
        'Payment uuid when payment is made by customer and is verified',
      total_customer_payable:
        'total_food_cost + total_taxes + total_packing_charges - discount_amount_applied + delivery_charges + transaction_charges',
      transaction_charges_rate: 'From .env: 3%',
    },
    coupon_details: {
      code: '20%OFF-COUPON',
      type: 'upto',
      level: 'global',
      coupon_id: 20,
      discount_percentage: 20,
      max_discount_rupees: 50,
      discount_amount_rupees: 0,
      min_order_value_rupees: 110,
      discount_amount_applied: 28.4,
      discount_share_amount_vendor: 0,
      discount_share_amount_speedyy: 28.4,
      discount_share_percentage_vendor: 0,
      discount_share_percentage_speedyy: 100,
    },
    total_food_cost: 142,
    delivery_charges: 59,
    transaction_charges: 5.18,
    order_packing_charge: 0,
    vendor_payout_amount: 142,
    total_packing_charges: 0,
    payment_transaction_id: '1254251',
    total_customer_payable: 177.78,
    transaction_charges_rate: 3,
    transaction_refund_charges: 5.18,
    vendor_cancellation_charges: 69.36000000000001,
    transaction_refund_charges_rate: 3,
  },
  payment_status: 'completed',
  payment_id: 'a8ad7410-5890-4f41-bc75-0a623d066efc',
  transaction_time: '2022-09-26T03:23:58.488Z',
  vendor_accepted_time: null,
  delivery_details: null,
  order_placed_time: '2022-09-26T03:23:58.493Z',
  vendor_accepted_start_time: '2022-09-26T03:24:33.493Z',
  vendor_accepted_end_time: '2022-09-26T03:24:58.493Z',
  order_pickedup_time: null,
  comments: null,
  reviewed_at: null,
  order_items: [
    {
      order_item_id: 1,
      menu_item_id: 11101,
      order_id: 1,
      quantity: 1,
      restaurant_id: 'b0909e52-a731-4665-a791-ee6479008805',
      name: 'Veg Burger',
      description: 'description',
      sub_category_id: 11,
      price: 100,
      veg_egg_non: 'veg',
      packing_charges: 0,
      is_spicy: true,
      serves_how_many: 1,
      service_charges: 10,
      item_sgst_utgst: 0,
      item_cgst: 0,
      item_igst: 0,
      item_inclusive: true,
      external_id: '123',
      allow_long_distance: true,
      image: {},
      order_variants: [
        {
          order_variant_id: 1,
          order_id: 1,
          order_item_id: 1,
          variant_group_id: 98,
          variant_group_name: 'menu item 1 variant 1',
          variant_id: 998,
          variant_name: 'variant group 1 variant name',
          is_default: true,
          serves_how_many: 1,
          price: 10,
          veg_egg_non: 'veg',
          created_at: '2022-09-26T08:53:58.475262+05:30',
          updated_at: '2022-09-26T08:53:58.475262+05:30',
        },
        {
          order_variant_id: 2,
          order_id: 1,
          order_item_id: 1,
          variant_group_id: 99,
          variant_group_name: 'menu item 1 variant 2',
          variant_id: 999,
          variant_name: 'variant group 1 variant name',
          is_default: true,
          serves_how_many: 1,
          price: 10,
          veg_egg_non: 'veg',
          created_at: '2022-09-26T08:53:58.475262+05:30',
          updated_at: '2022-09-26T08:53:58.475262+05:30',
        },
      ],
      order_addons: [
        {
          order_addon_id: 1,
          order_id: 1,
          order_item_id: 1,
          addon_name: 'addon name 1',
          addon_id: 7767,
          addon_group_name: 'addon group name',
          addon_group_id: 77,
          sequence: 1,
          price: 12,
          veg_egg_non: 'veg',
          sgst_rate: 0,
          cgst_rate: 0,
          igst_rate: 0,
          gst_inclusive: true,
          external_id: '76777',
          created_at: '2022-09-26T08:53:58.475262+05:30',
          updated_at: '2022-09-26T08:53:58.475262+05:30',
        },
        {
          order_addon_id: 2,
          order_id: 1,
          order_item_id: 1,
          addon_name: 'addon name 2',
          addon_id: 7768,
          addon_group_name: 'addon group name',
          addon_group_id: 77,
          sequence: 1,
          price: 10,
          veg_egg_non: 'veg',
          sgst_rate: 0,
          cgst_rate: 0,
          igst_rate: 0,
          gst_inclusive: true,
          external_id: '76778',
          created_at: '2022-09-26T08:53:58.475262+05:30',
          updated_at: '2022-09-26T08:53:58.475262+05:30',
        },
      ],
    },
  ],
  restaurant_details: {
    restaurant_name: 'Food',
    image: {name: '25887d2c-4dc4-42a1-9e3d-62a6f0c33cae.jpg'},
    latitude: 19.158672,
    longitude: 72.89071,
  },
};

export const restaurantDetails = {
  id: 'b0909e52-a731-4665-a791-ee6479008805',
  name: 'Food',
  lat: 19.158672,
  long: 72.89071,
  partner_id: 'cc37e5e6-0a0e-4e73-848c-aeed4ad2a695',
  status: 'active',
  image: {name: '25887d2c-4dc4-42a1-9e3d-62a6f0c33cae.jpg'},
  images: [{name: '25887d2c-4dc4-42a1-9e3d-62a6f0c33cae.jpg'}],
  orders_count: 0,
  like_count: 0,
  like_count_label: '0',
  rating: 0, //! BACKWARD_COMPATIBLE
  delivery_time: null,
  city_id: '25887d2c-4dc4-42a1-9e3d-62a6f0c33cae',
  area_id: '25887d2c-4dc4-42a1-9e3d-62a6f0c33cae',
  cuisine_ids: [],
  is_pure_veg: true,
  cost_of_two: 100,
  allow_long_distance: true,
  packing_charge_type: 'none',
  packing_charge_item: [
    {
      item_name: 'Paneer Tikka',
      item_price: 120,
      packing_image: {name: '25887d2c-4dc4-42a1-9e3d-62a6f0c33cae.jpg'},
      packing_charge: 2.5,
    },
  ],
  packing_charge_order: {
    packing_image: {name: '25887d2c-4dc4-42a1-9e3d-62a6f0c33cae.jpg'},
    packing_charge: 2.5,
  },
  default_preparation_time: 10,
  poc_number: null,
  all_time_rating_order_count: 0,
  hold_payout: false,
  created_at: '2022-04-27T04:54:01.873Z',
  updated_at: '2022-04-27T04:54:01.873Z',
  is_deleted: false,
  draft_section: null,
  preferred_language_ids: null,
  tnc_accepted: null,
  user_profile: null,
  owner_name: null,
  owner_contact_number: null,
  owner_email: null,
  owner_is_manager: null,
  manager_name: null,
  manager_contact_number: null,
  manager_email: null,
  invoice_email: null,
  location: null,
  postal_code: null,
  postal_code_verified: null,
  state: null,
  read_mou: null,
  document_sign_number: null,
  document_sign_number_verified: null,
  menu_document_type: null,
  menu_documents: null,
  scheduling_type: null,
  approved_by: null,
  status_comments: null,
  catalog_approved_by: null,
  fssai_has_certificate: null,
  fssai_application_date: null,
  fssai_ack_number: null,
  fssai_ack_document_type: null,
  fssai_ack_document: null,
  fssai_expiry_date: null,
  fssai_cert_number: null,
  fssai_cert_verified: null,
  fssai_cert_document_type: null,
  fssai_cert_document: null,
  fssai_firm_name: null,
  fssai_firm_address: null,
  gst_category: null,
  pan_number: null,
  pan_number_verified: null,
  pan_owner_name: null,
  pan_document_type: null,
  pan_document: null,
  has_gstin: null,
  gstin_number: null,
  gstin_number_verified: null,
  gstin_document_type: null,
  gstin_document: null,
  business_name: null,
  business_address: null,
  bank_account_number: null,
  ifsc_code: null,
  ifsc_verified: null,
  bank_document_type: null,
  kyc_document_type: null,
  bank_document: null,
  kyc_document: null,
  city: null,
};

export const successfull_cart_response = {
  cart_status: true,
  any_special_request: 'Dont ring door bell',
  coupon_code: '20%OFF-COUPON',
  coupon_id: 20,
  customer_details: {
    customer_id: '33c6fdbc-8df6-4541-9d3f-f9e5ba4c0242',
    customer_device_id: '12412423432424413213123',
    customer_address_id: 'bd7e895f-0f7d-4dbe-9408-285abf5986ce',
    customer_addresses: [
      {
        apartment_road_area: 'apartment_road_area.',
        city: 'Mumbai',
        country: 'India',
        created_at: '2022-02-24T06:25:22.096Z',
        customer_id: '33c6fdbc-8df6-4541-9d3f-f9e5ba4c0242',
        directions: 'ABC',
        house_flat_block_no: 'HouseNumber,Wing,Block Number,',
        id: 'bd7e895f-0f7d-4dbe-9408-285abf5986ce',
        deliverable: true,
        latitude: 19.158672,
        longitude: 72.89071,
        name: 'Mohit',
        pincode: '0',
        state: 'Maharashtra',
        updated_at: '2022-02-24T06:25:22.096Z',
        delivery_details: {
          pickup_eta: 1,
          drop_eta: 35,
          deliverable: true,
          delivery_cost: 59,
        },
      },
    ],
    delivery_address: {
      apartment_road_area: 'apartment_road_area.',
      city: 'Mumbai',
      country: 'India',
      created_at: '2022-02-24T06:25:22.096Z',
      customer_id: '33c6fdbc-8df6-4541-9d3f-f9e5ba4c0242',
      directions: 'ABC',
      house_flat_block_no: 'HouseNumber,Wing,Block Number,',
      id: 'bd7e895f-0f7d-4dbe-9408-285abf5986ce',
      deliverable: true,
      latitude: 19.158672,
      longitude: 72.89071,
      name: 'Mohit',
      pincode: '0',
      state: 'Maharashtra',
      updated_at: '2022-02-24T06:25:22.096Z',
      delivery_details: {
        pickup_eta: 1,
        drop_eta: 35,
        deliverable: true,
        delivery_cost: 59,
      },
    },
  },
  menu_items_available: true,
  menu_items: [
    {
      menu_item_id: 11101,
      restaurant_id: 'b0909e52-a731-4665-a791-ee6479008805',
      menu_item_name: 'Veg Burger',
      sub_category_id: 111,
      description: 'description',
      price: 100,
      veg_egg_non: 'veg',
      packing_charges: 10,
      is_spicy: true,
      serves_how_many: 1,
      service_charges: 10,
      item_sgst_utgst: 0,
      item_cgst: 0,
      item_igst: 0,
      item_inclusive: true,
      disable: false,
      image: {},
      external_id: '123',
      allow_long_distance: true,
      next_available_after: '2022-04-27T04:54:01.883Z',
      is_deleted: false,
      variant_groups: [
        {
          variant_group_id: 98,
          variant_group_name: 'menu item 1 variant 1',
          variants: [
            {
              variant_id: 998,
              variant_group_id: 98,
              variant_name: 'variant group 1 variant name',
              is_default: true,
              price: 10,
              veg_egg_non: 'veg',
              in_stock: true,
              serves_how_many: 1,
              is_selected: true,
            },
          ],
          is_selected: true,
        },
        {
          variant_group_id: 99,
          variant_group_name: 'menu item 1 variant 2',
          variants: [
            {
              variant_id: 999,
              variant_group_id: 99,
              variant_name: 'variant group 1 variant name',
              is_default: true,
              price: 10,
              veg_egg_non: 'veg',
              in_stock: true,
              serves_how_many: 1,
              is_selected: true,
            },
          ],
          is_selected: true,
        },
      ],
      addon_groups: [
        {
          addon_group_id: 77,
          addon_group_name: 'addon group name',
          min_limit: 2,
          max_limit: 3,
          free_limit: 1,
          sequence: 1,
          addons: [
            {
              addon_id: 7768,
              addon_name: 'addon name 2',
              sequence: 1,
              price: 10,
              veg_egg_non: 'veg',
              in_stock: true,
              sgst_rate: 0,
              cgst_rate: 0,
              igst_rate: 0,
              gst_inclusive: true,
              external_id: '76778',
              is_selected: true,
            },
            {
              addon_id: 7769,
              addon_name: 'addon name 3',
              sequence: 1,
              price: 10,
              veg_egg_non: 'veg',
              in_stock: true,
              sgst_rate: 0,
              cgst_rate: 0,
              igst_rate: 0,
              gst_inclusive: true,
              external_id: '76779',
              is_selected: false,
            },
            {
              addon_id: 7767,
              addon_name: 'addon name 1',
              sequence: 1,
              price: 12,
              veg_egg_non: 'veg',
              in_stock: true,
              sgst_rate: 0,
              cgst_rate: 0,
              igst_rate: 0,
              gst_inclusive: true,
              external_id: '76777',
              is_selected: true,
            },
          ],
          is_selected: true,
        },
      ],
      menu_item_slots: null,
      quantity: 1,
      variants_total_cost_without_tax: 20,
      variants_instock: true,
      variants_count: 2,
      addons_total_cost_without_tax: 22,
      addons_total_tax: 0,
      addons_instock: true,
      addons_count: 2,
      total_tax: 0,
      total_cost_without_tax: 152,
      in_stock: true,
    },
  ],
  menu_items_count: 1,
  delivery_time: 47,
  restaurant_details: {
    restaurant_id: 'b0909e52-a731-4665-a791-ee6479008805',
    restaurant_name: 'Burger King',
    restaurant_status: 'active',
    like_count: 100000,
    like_count_label: '100.0K',
    rating: 0, //! BACKWARD_COMPATIBLE
    availability: {
      is_holiday: false,
      is_open: true,
    },
    latitude: 19.158672,
    longitude: 72.89071,
  },
  invoice_breakout: {
    menu_items: [
      {
        item_name: 'Veg Burger',
        item_quantity: 1,
        item_cgst: 0,
        item_sgst: 0,
        item_igst: 0,
        item_price: 100,
        total_item_amount: 120,
        item_tax_amount: 0,
        item_packing_charges: 0,
        item_packing_rate: 10,
        addon_groups: [
          {
            addon_group_id: 77,
            addon_group_name: 'addon group name',
            addons: [
              {
                addon_id: 7768,
                addon_name: 'addon name 2',
                addon_cgst: 0,
                addon_sgst: 0,
                addon_igst: 0,
                addon_price: 10,
                addon_tax_amount: 0,
              },
              {
                addon_id: 7767,
                addon_name: 'addon name 1',
                addon_cgst: 0,
                addon_sgst: 0,
                addon_igst: 0,
                addon_price: 12,
                addon_tax_amount: 0,
              },
            ],
            free_limit: 1,
            total_addon_price: 12,
            total_addon_tax_amount: 0,
          },
        ],
        variants: [
          {
            variant_group_id: 98,
            variant_group_name: 'menu item 1 variant 1',
            variant_id: 998,
            variant_name: 'variant group 1 variant name',
            variant_price: 10,
          },
          {
            variant_group_id: 99,
            variant_group_name: 'menu item 1 variant 2',
            variant_id: 999,
            variant_name: 'variant group 1 variant name',
            variant_price: 10,
          },
        ],
        total_variant_cost: 20,
        total_addon_group_price: 12,
        total_addon_group_tax_amount: 0,
        total_individual_food_item_cost: 132,
        total_individual_food_item_tax: 0,
      },
    ],
    order_packing_charge: 0,
    total_food_cost: 132,
    total_packing_charges: 0,
    total_tax: 0,
    delivery_charges: 59,
    transaction_charges_rate: 3,
    transaction_refund_charges_rate: 3,
    transaction_charges: 4.94,
    transaction_refund_charges: 4.94,
    total_customer_payable: 164.6,
    vendor_payout_amount: 127.06,
    vendor_cancellation_charges: 68.88,
    description: {
      version: '0.0.2',
    },
    coupon_details: {
      coupon_id: 20,
      code: '20%OFF-COUPON',
      type: 'upto',
      level: 'global',
      min_order_value_rupees: 110,
      max_discount_rupees: 50,
      discount_percentage: 20,
      discount_amount_rupees: 0,
      discount_share_percentage_vendor: 0,
      discount_share_percentage_speedyy: 100,
      discount_amount_applied: 26.4,
      discount_share_amount_speedyy: 26.4,
      discount_share_amount_vendor: 0,
    },
  },
};
