INSERT INTO "global_var" ("key","value","type","editable","description","updated_by")
VALUES
('SERVICEABILITY_RADIUS_IN_METRES', '50000', 'number', 'true', 'Restaurant serviceability radius in metres', 'system'),
('CART_MAX_TOTAL_QUANTITY', '100', 'number', 'true', 'Cart maximum allow quantity', 'system'),
('CASHFREE_PAYOUT_MIN_BALANCE', '1000', 'number', 'true', 'Payout minimum required balance', 'system'),
('PAYMENT_GATEWAY', 'CASHFREE', 'string', 'true', 'Payment gateway name', 'system'),
('DELIVERY_SERVICE', 'shadowfax', 'string', 'true', 'Delivery service name', 'system'),
('ORDER_CANCELLATION_DURATION_IN_SECONDS', '120', 'number', 'true', 'Order cancellation duration in seconds', 'system'),
('ORDER_CANCELLATION_DELAY_IN_SECONDS', '5', 'number', 'true', 'Order cancellation delay in seconds', 'system'),
('ORDER_ACCEPT_DURATION_IN_SECONDS', '600', 'number', 'true', 'Vendor Order acceptance duration in seconds', 'system'),
('ORDER_REATTEMPT_DURATION_IN_SECONDS', '300', 'number', 'true', 'Vendor Order acceptance retry in seconds', 'system'),
('ORDER_VENDOR_RETRY_ATTEMPTS', '3', 'number', 'true', 'Max Vendor Order acceptance notification retries', 'system'),
('SUPER_ADMIN_EMAIL', 'test@speedyy.com', 'string', 'true', 'super adming email id', 'system'),
('CATALOG_TEAM_EMAIL', 'test@speedyy.com', 'string', 'true', 'catalog team email id', 'system'),
('BACKEND_TEAM_EMAIL', 'test@speedyy.com', 'string', 'true', 'backend team email id', 'system'),
('ORDER_NOT_ACCEPT_ADMIN_EMAIL', 'test@speedyy.com', 'string', 'true', 'If vendor does not accept the order an email will be forwarded to this email', 'system'),
('PAYOUT_REPORT_ADMIN_EMAIL', 'test@speedyy.com', 'string', 'true', 'payout report will be forwarded to this email', 'system'),
('SUPPORT_CONTACT', '0000000000', 'string', 'true', 'support contact phone number', 'system'),
('SUBSCRIPTION_AUTHORIZATION_AMOUNT_IN_RUPEES', '10', 'number', 'true', 'subscription emandate authorization cost', 'system'),
('SUBSCRIPTION_RETURN_URL', 'https://vendor.dev.speedyy.com/login', 'string', 'true', 'when subscription emanded is created, user will be redirected to this url', 'system'),
('SUBSCRIPTION_EXPIRY_INTERVAL_IN_MONTHS', '24', 'number', 'true', 'subscription will be expired after this given months', 'system'),
('SUBSCRIPTION_FIRST_PAYMENT_DATE_INTERVAL_IN_DAYS', '2', 'number', 'true', 'subscription first payment will be deducted after given days', 'system'),
('SUBSCRIPTION_END_TIME_GRACE_PERIOD_IN_DAYS', '2', 'number', 'true', 'subscription grace period in days', 'system'),
('SUBSCRIPTION_VERFIY_NEW_PAYMENT_AFTER_SECONDS', '300', 'number', 'true', 'subscription payment will be reveryfied after given seconds', 'system'),
('SUBSCRIPTION_VERFIY_NEW_PAYMENT_MAX_ATTEMPTS', '3', 'number', 'true', 'subscription reverify max attempts', 'system'),
('NOTIFY_SUBSCRIBERS_BEFORE_DAYS', '7', 'number', 'true', 'notify subscribers before given days', 'system'),
('CUSTOMER_CANCELLATION_POLICY', '{"terms_conditions":"https://www.speedyy.com/terms-conditions/","note":"If you cancel within 60 seconds of placing your order, a 100% refund will be issued. No refund for cancellation made after 60 seconds."}', 'json', 'true', 'cancellation policy details for customer', 'system'),
('VENDOR_CANCELLATION_POLICY', '{"terms_conditions":"https://www.speedyy.com/terms-conditions/","note":"100% cancellation fee will be applicable if you cancel the order anytime after accepting the order"}', 'json', 'true', 'cancellation policy details for vendor', 'system'),
('STRING-TYPE', 'test-string', 'string', 'true', 'String key and valu', 'system'),
('FILE-TYPE', '{"name":"28a029bb-ebd0-4899-9291-6c16aa286d08.jpg","bucket":"speedyy-dev-core-api-public","path":"global_var_files/"}', 'file', 'true', 'file key and value', 'system'),
('ARRAY-TYPE', '[{ "name": "Alice", "age": 25},{ "name": "Bob", "age": 30},{ "name": "Charlie", "age": 20}]', 'json', 'true', 'array key and value', 'system'),
('JSON-TYPE', '{"name": "John Doe", "age": 30, "isMarried": false}', 'json', 'true', 'json key and value', 'system'),
('NUMBER-TYPE', '100', 'number', 'true', 'number key and value', 'system'),
('DUMMY_MENU_ITEM_IMAGE', '{"name":"6fc40636-f034-4267-81c9-c2537923dc7f.jpg","bucket":"speedyy-dev-core-api-public","path":"global_var_files/"}', 'file', 'true', 'Dummy Menu Image', 'system'),
('HIDE_PENDING_ORDERS_DURATION_IN_MINS', '120', 'number', 'true', 'Duration after which pending orders will be hidden', 'system'),
('DEFAULT_PAGE_SIZE_RESTAURANT', '30', 'number', 'true', 'Default pagination size for restaurant filtering', 'system')

ON CONFLICT(KEY) DO UPDATE SET VALUE = COALESCE(GLOBAL_VAR.VALUE,EXCLUDED.VALUE);
